const actionsTypesOneQuestion = {
  LOAD_SUCCESS_QUESTION: "LOAD_SUCCESS_QUESTION",
  LOAD_FAILURE_QUESTION: "LOAD_FAILURE_QUESTION",
  ////
  LOAD_QUESTION_CLEAR: "LOAD_QUESTION_CLEAR",
};

export default actionsTypesOneQuestion